"""Normalised digests of every Codex file a released `mb` wrote at an old Codex path.

Generated by `scripts/codex_known_files.py`, which replays each release's own
writers in a temporary HOME; do not edit by hand. Rerun it with `--write` after
a release changes what those writers produce. Keys are the file's folder and
name; values are `mb.codex.normalised_generated_digest` results.
"""

from __future__ import annotations

RELEASES_REPLAYED: tuple[str, ...] = (
    "oe-v0.3.14",
    "oe-v0.3.15",
    "oe-v0.3.16",
    "oe-v0.3.17",
    "oe-v0.3.18",
    "oe-v0.3.19",
    "oe-v0.3.20",
    "oe-v0.3.21",
    "oe-v0.3.22",
    "oe-v0.3.23",
    "oe-v0.3.24",
    "oe-v0.3.25",
    "oe-v0.3.26",
    "oe-v0.3.27",
    "oe-v0.3.28",
    "oe-v0.3.29",
    "oe-v0.3.30",
    "oe-v0.3.31",
    "oe-v0.3.32",
    "oe-v0.3.33",
    "oe-v0.3.34",
    "oe-v0.3.35",
    "oe-v0.3.36",
    "oe-v0.3.37",
    "oe-v0.3.38",
    "oe-v0.3.39",
    "oe-v0.3.40",
    "oe-v0.3.41",
    "oe-v0.3.42",
    "oe-v0.3.43",
    "oe-v0.3.44",
    "oe-v0.4.0",
    "oe-v0.4.1",
    "oe-v0.4.2",
    "oe-v0.4.3",
    "oe-v0.5.0",
    "oe-v0.5.1",
    "oe-v0.5.2",
    "oe-v0.5.3",
    "oe-v0.6.0",
    "oe-v0.6.1",
    "oe-v0.6.2",
    "oe-v0.6.3",
)

KNOWN_FILE_DIGESTS: dict[str, frozenset[str]] = {
    ".codex-plugin/plugin.json": frozenset(
        {
            "67267e3b6c781a603c73199c34dd7fdd1d63475370606a656b17358a884d83aa",
            "e894857e975b2c87ffda5ccf93a3439c289eeb5fb781ce28ad09fb401530c7c9",
            "f4c91e1b7a2b87c386b6dadc280a9cc6ed3b4290c12ec9be75dc00826203dc06",
        }
    ),
    "commands/mb-checkpoint.md": frozenset(
        {
            "4f31965cf84e9f965441cbc80e895445c87eb817f16ac1150d2f175b8e8505af",
            "b579fc24912b236d6b30f14633a405b80cec8d87e395ff1d12683ee33239fdc7",
            "efdda00ae8c2e4f1b802b4f355863dd97ab7b07422da2120fdf0b4e37a5771af",
        }
    ),
    "commands/mb-doctor.md": frozenset(
        {
            "1fb510d751e41a7967f64dea81d66d7acc15f54d8da625ff6b1a0ebceea5bea5",
            "711e61aa99383a2258179dc078efe615ca56b3e7df9fe58f48639a93a2552440",
            "d913ecb75e8cdb1b61c38c89f840b6b22ccb36438ff7a6d1a206ac19b39da597",
            "f46f6d936d1e49991386b8d37841598927db12f1503536ce3e917a89dd272d6a",
        }
    ),
    "commands/mb-end.md": frozenset(
        {
            "17b1043e86381e5850a699445c2dc0147706f427db33bbcb0d286fee21021a65",
            "3b2ffb88bc8500b481d333f9442585cb9a75e081dc6c7d0b771362727ac6817d",
            "96d879a31a89cfe7979d20e2028657d19febeaefc0163e6c7b5ab6b46b3bb4cf",
            "bf3ff5f0fc4befe35a773bf0cd8b3b2fce1bb5bccab4b2b9f5431d43a8731c9a",
            "e359e3e7577f2bf6035febf469b0f930db9a06cf4b55674132d4bc415528e863",
        }
    ),
    "commands/mb-help.md": frozenset(
        {
            "38bd3525f7565218668f605b96e3d2908b6ffb28bd913ab693ff0e0d9995b463",
            "3c84b67106ef3e8a67060d9c1403179f8365b35cfae4fd252d98231a9ebb848d",
            "c0fe087fbb4166a1d5b08fa7222067d066ba92f8fcd922302f65b58ecfc6bfd3",
            "fe604d96787bd156cadb7e86cf12875177a8c3a08b51d469dac52faf864006f7",
        }
    ),
    "commands/mb-setup.md": frozenset(
        {
            "27f40b379578de207961abe1fcf3e18c85e090e8f28d7edd6b9e388498ebc688",
            "4331b68913794435d09b1283f4d09949e40b07b100fb7b9d584122c8350ae1cf",
            "6786b9348de19d065a495b8ca336a5e6f04a3434b372e2822361dd90f4334762",
            "e381280b7a7dd655937b5180bf01bb4f39be053d2ba45ec776982b7b845b16ab",
        }
    ),
    "commands/mb-start.md": frozenset(
        {
            "1d12b9299b9e21aa2883dae134ade7b8c92b50d39606d05c3ee78c354dfde150",
            "36d9fea83c8fc6c31fc1948839cf993ba7b1a6967f97d874518aa75265634ba1",
            "dd28e85fe9b8bf355b774a15827f61f70274ecf4dcf5d8bc0322914d11f93d2a",
            "dec438937cce2a5f94d640da230211bfec5b5c94808790ace35f24c8e60fd5a0",
        }
    ),
    "commands/mb-status.md": frozenset(
        {
            "2f7d8e451f5edc395cd315e07bf16b40e5bf51df43edbbac5230d60414b28823",
            "88bb0eee136a5280551a5f425624d7af8f6c5358f73d64921b103553f8b42f36",
            "9193e0181b1ae335c84d7826a128e091640a1e36e787047afd48aa74ec0bac40",
            "c3bfde83167bfedf5c4fafbfa0d7565fa0d5a85955427c04cdd31c6a643261ce",
        }
    ),
    "commands/mb-think.md": frozenset(
        {
            "3bdb84f732ffd3eec198dc0195c68860f3eefa46817f23c4931a4094d0c5d7ef",
            "6ba305ac13da36f3084232fc67a44321d10498509480007dfb0dd655f77e20fb",
            "8fbd24a315d55fc7ea9fb29ae0d9da8a8509d1beb19c9983ec00db9a9fcc6c68",
            "a5864b0b09729e0092e4ba9960ea20c1f6b820c485d56b421539a67df3a050a3",
        }
    ),
    "commands/mb-update.md": frozenset(
        {
            "e67f355be3b403fd0b06c0f4fe4a7073eb393514c45ecbddca9239def018ab94",
            "f514ed55107418bacf5c3477063f151a134e58f61f5b555bba7e0f7b290ef7c1",
            "fa386b4a1fac12003bd1d502faeb489326a6e20a76806ac1af26db5d11bba578",
            "fdfc1aebc89956606b61b1e47e31b21e4d645e77ba15acdd4beab278a36b6fbc",
        }
    ),
    "commands/mb-validate.md": frozenset(
        {
            "2c6dca4a00c1db72a8976f3c143aad663477d68bc04189f2adcf0d27540c5b4f",
            "ab1d927d9e1d354ebc0ed62361c2d2247237ededa632a14e9b83ee64664eca7e",
            "d31bf422ea3e0e316086cc77b7f6b6af23b82eeae0edd181c85e165841295965",
        }
    ),
    "commands/mb-workflows.md": frozenset(
        {
            "7f84c37835201762b5ff8befb79fc0e96ed5e6434b39ca5eba0de3409119b671",
            "962599842280fd34e7362e2a62620fe0307382f3f89609cbb9b2e57a15b1efc7",
            "a4c7753b57e18d7069142927270ba41e78138bc903a6d3540cdd8a811fd80b77",
        }
    ),
    "google-ads-search-launch/SKILL.md": frozenset(
        {
            "0af05783cced1c1b6a20730e78d50e8d302516ea97683514c6f3272176158271",
        }
    ),
    "main-branch-owner-loop/SKILL.md": frozenset(
        {
            "0b74687f25096369ef1608bfd0c71814878695e14765ab030ec35b814856d8a5",
            "5618a738840c11bd9d01c5eb3ce4b7fa13d59a9e81b9170eb7defd4b3532e2a4",
            "9d972516d08935acc7a84f8fc2a19e5b279f7efb9c8123ada35034cc32485ad6",
            "a3abd80716f8875575bfe77cce4bdb9c7eaa67a6577632d0233f999dc3ec3a15",
            "ff61d70ce7c71cd8095d68ac97ee03ba45ce01138da12d40ab8a5801e89d8a28",
        }
    ),
    "main-branch/SKILL.md": frozenset(
        {
            "542090999af532eaa17712ce76cc5499b6ba39efd8a49ab9a324432304e912f2",
            "7d59200eddef557722da6e66c314e7b00c07b66e8ce5614afaacea1fc20b48de",
            "c553b8494e9362bd8774154dde0548bbe462e5fab7e4b77c5d7ce701b2f39a3e",
        }
    ),
    "plugins/marketplace.json": frozenset(
        {
            "075e5711933c06c4956cb5a58713ef6dbce5818df5508c0c0c287c3f82c37b09",
            "542bd5186e819d678abdbbfbcb9bd3bf4f4e8e08f1ea9b03372aca393923ac03",
            "b6dea39bd3566bd5ef0a4a923cedf02fbc6de7f79ed3e455f1219dce0d08421b",
        }
    ),
    "references/workflow-inventory.md": frozenset(
        {
            "4e5516186cba8036f00ee990ecaef3743d9e3517eb7203689926170cfc6bcb8c",
            "a5bfe7d2ea3bc6a6a14a3a85a4b7fa3cd724995c7a7232e99237a2adfcb24010",
        }
    ),
    "ship-bet/SKILL.md": frozenset(
        {
            "4ae4326fad29397885b83cd15423a7f7dc75cb77464d3fcf163ee0134d53e14a",
        }
    ),
    "weekly-review/SKILL.md": frozenset(
        {
            "d34919f96abd393db441be112be862cf67db9c424e637ea34fa370fd4b5809fb",
        }
    ),
}
